<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Catalog [
<!ELEMENT Book (First, Title,Price)>
<!ELEMENT Title (#PCDATA)>
<!ELEMENT Price (#PCDATA)>
]>
<Catalog xmlns = "http://www.aptechworldwide.com">
<Book>
<Title type = "Fiction">Evening in Paris</Title>
<Price>$123</Price>
</Book>
<Book>
<Title type = "Non-Fiction">Return to Earth</Title>
<Price xmlns = "http://www.aptech.ac.in">$23</Price>
<Title type = "Non-Fiction">Journey to the center of 
the Moon</Title>
<Price>$123</Price>
</Book>
</Catalog>